site_name: macdwm
site_description: A minimal macOS tiling window manager inspired by dwm
site_author: sunnybharne
site_url: https://sunnybharne.github.io/macdwm
repo_url: https://github.com/sunnybharne/macdwm
repo_name: sunnybharne/macdwm

docs_dir: docs-content

theme:
  name: slate

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user-guide.md
  - Releases: releases.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - codehilite
  - fenced_code
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

