name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build macdwm
      run: |
        swift build --configuration release --disable-sandbox
        
    - name: Test binary
      run: |
        # Test that the binary exists and is executable
        if [ -f .build/release/macdwm ]; then
          echo "Binary exists and is executable"
          ls -la .build/release/macdwm
        else
          echo "Binary not found!"
          exit 1
        fi
        echo "Binary built successfully"
        
    - name: Check binary size
      run: |
        ls -lh .build/release/macdwm
        size=$(stat -f%z .build/release/macdwm)
        echo "Binary size: $size bytes"
        if [ $size -gt 1048576 ]; then
          echo "Warning: Binary is larger than 1MB"
        fi
